### ISSUE TITLE
ValueError: could not convert string to float: '0 group-title="AF: Afghanistan"'

### ISSUE THREAD

**Issue by max-rocket-internet** [globocom/m3u8#128]
I'm running latest release:

```python
>>> m3u8_obj = m3u8.load('sources/bug.m3u')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/m3u8/__init__.py", line 45, in load
    return _load_from_file(uri)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/m3u8/__init__.py", line 82, in _load_from_file
    return M3U8(raw_content, base_uri=base_uri)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/m3u8/model.py", line 141, in __init__
    self.data = parse(content, strict)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/m3u8/parser.py", line 117, in parse
    _parse_extinf(line, data, state, lineno, strict)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/m3u8/parser.py", line 198, in _parse_extinf
    state['segment']['duration'] = float(duration)
ValueError: could not convert string to float: '0 group-title="AF: Afghanistan"'
```

And `bug.m3u` is random IPTV playlist from the internet:

```
#EXTM3U
#EXTINF:0 group-title="AF: Afghanistan",AF: 218
http://95.85.47.43/218tv/tracks-v1a1/index.m3u8
#EXTINF:0 group-title="AF: Afghanistan",AF: 218 (1+)
http://egyman.net:1978/live/180118/180118/6701.m3u8
#EXTINF:0 group-title="AF: Afghanistan",AF: 2S TV
http://212.8.249.144:8711/live/imanianMCS45NEW/0IyBEKkMsy/5277.m3u8
#EXTINF:0 group-title="AF: Afghanistan",AF: AL FORAT
http://egyman.net:1978/live/180118/180118/6663.m3u8
#EXTINF:0 group-title="AF: Afghanistan",AF: AL HADATH
http://starmena.ercdn.net/libya-alhadath/libya-alhadath.m3u8
#EXTINF:0 group-title="AF: Afghanistan",AF: AL HURRA
http://egyman.net:1978/live/180118/180118/6662.m3u8
```

**Comment by mauricioabreu** [comment]
It does not seem to be like an error in the library but in the file.

Here is the draft for the m3u[8] format: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.1

> The EXTINF tag specifies the duration of a Media Segment.  It applies
   only to the next Media Segment.  This tag is REQUIRED for each Media
   Segment.  Its format is:
   #EXTINF:<duration>,[<title>]

**Comment by max-rocket-internet** [comment]
OK makes sense.

It might be nice to raise a proper exception for this though, so it can be caught and dealt with easily.  Something like `TrackMetadataError` or something?

**Comment by mauricioabreu** [comment]
With `load` it won't be possible.
I guess you need to use the `M3U8` class and initiate it passing `strict=True`.

https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L139

**Comment by mauricioabreu** [comment]
What is your opinion @max-rocket-internet ?

**Comment by max-rocket-internet** [comment]
I still think `load` and `loads` should handle badly formatted data with a proper exception but no worries, I think for me this issue is resolved. Thanks for the swift response 🙂
