### ISSUE TITLE
[bug] httpclient.py: cannot handle utf-8 data when using `m3u8.load()`

### ISSUE THREAD

**Issue by kmahyyg** [globocom/m3u8#241]
```
D:\GitBins\<REDACTED FOR SENSITIVE INFORMATION>> python .\test-heartbeat.py
<REDACTED FOR SENSITIVE INFORMATION>
Traceback (most recent call last):
  File ".\test-heartbeat.py", line 105, in <module>
    <REDACTED FOR SENSITIVE INFORMATION>.run_it()
  File ".\test-heartbeat.py", line 98, in run_it
    self.parse_m3u8_info()
  File ".\test-heartbeat.py", line 71, in parse_m3u8_info
    M3 = m3u8.load(i[1]).data
  File "C:\Python38\lib\site-packages\m3u8\__init__.py", line 46, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "C:\Python38\lib\site-packages\m3u8\httpclient.py", line 27, in download
    resource = opener.open(uri, timeout=timeout)
  File "C:\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Python38\lib\http\client.py", line 1104, in putrequest
    self._output(self._encode_request(request))
  File "C:\Python38\lib\http\client.py", line 1184, in _encode_request
    return request.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 25-34: ordinal not in range(128)
```

Hello, If the m3u8 data in response contains any UTF-8 based CJK chars, the default http client in Python will throw an exception as shown above. Please try to change to another http request library like `requests`. 

For temporary solution, the developers might need to deal like this:

```python
import requests

respdata = requests.get(m3u8_URL).text
m3u8file = m3u8.loads(respdata)
```

**Comment by mauricioabreu** [comment]
Hello @kmahyyg 

For this reason, we have a way to use a different HTTP client: https://github.com/globocom/m3u8#using-different-http-clients

**Comment by kmahyyg** [comment]
Thanks for your response.

Why not just build a general version working for everyone?
