### ISSUE TITLE
broken python3 support

### ISSUE THREAD

**Issue by audetto** [globocom/m3u8#55]
https://github.com/globocom/m3u8/commit/4e3e6726ea74ba7ad44e4d552c9c853ea31da97a

has broken python3 support

import exceptions

is not needed and "exceptions.Exception" is now simply "Exception"

in parser.py

**Comment by ghtyrant** [comment]
Same for me.

```
Traceback (most recent call last):
  File "twitch_live_url.py", line 6, in <module>
    import m3u8
  File "/home/fabian/.virtualenvs/bcgsrebroadcaster/lib/python3.5/site-packages/m3u8/__init__.py", line 22, in <module>
    from m3u8.model import M3U8, Playlist, IFramePlaylist, Media, Segment
  File "/home/fabian/.virtualenvs/bcgsrebroadcaster/lib/python3.5/site-packages/m3u8/model.py", line 16, in <module>
    from m3u8 import parser
  File "/home/fabian/.virtualenvs/bcgsrebroadcaster/lib/python3.5/site-packages/m3u8/parser.py", line 11, in <module>
    import exceptions
ImportError: No module named 'exceptions'
```

```
% pip install --upgrade git+https://github.com/globocom/m3u8.git
Collecting git+https://github.com/globocom/m3u8.git
  Cloning https://github.com/globocom/m3u8.git to /tmp/pip-xnftyxmz-build
Requirement already up-to-date: iso8601 in /home/fabian/.virtualenvs/bcgsrebroadcaster/lib/python3.5/site-packages (from m3u8==0.2.6)
Installing collected packages: m3u8
  Found existing installation: m3u8 0.2.6
    Uninstalling m3u8-0.2.6:
      Successfully uninstalled m3u8-0.2.6
  Running setup.py install for m3u8
Successfully installed m3u8-0.2.6
```

```
% python --version
Python 3.5.0
```

**Comment by leandromoreira** [comment]
It was done! thanks @audetto https://pypi.python.org/pypi/m3u8/0.2.7
